modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pixelmonwar"
version="0.0.0"
displayName="Pixelmon War"
displayURL="https://github.com/EnvyWare" # URL HERE
credits="https://github.com/EnvyWare" # Your name here
authors="https://github.com/EnvyWare" # Your name here
description='''
Makes Pixelmon fight you upon punching them.
'''

[[dependencies.pixelmonwar]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonwar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.pixelmonwar]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.2,)"
    ordering="NONE"
    side="BOTH"